version: "3.9"
services:
  jellyfin:
    image: ghcr.io/aleksasiriski/jellyfin-rffmpeg:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:8096:8096 # public should access via reverse proxy
    volumes:
      - jellyfin-conf:/config:z
      - /var/storage/media:/var/storage/media # optional media folder
    restart: always
  nfs-server:
    image: ghcr.io/obeone/nfs-server:latest
    cap_add:
      - SYS_ADMIN
    environment:
      - TZ=Europe/Berlin
      - NFS_EXPORT_0="/config/transcodes      *(rw,sync,no_subtree_check,no_root_squash)"
      - NFS_EXPORT_1="/config/data/subtitles  *(rw,sync,no_subtree_check,no_root_squash)"
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:2049:2049
    volumes:
      - jellyfin-conf:/config:z
    restart: always
  rffmpeg-autoscaler:
    image: ghcr.io/aleksasiriski/rffmpeg-autoscaler:latest
    depends_on:
      - jellyfin
    environment:
      - TZ=Europe/Berlin
      - JELLYFIN_HOST=$JELLYFIN_LAN_ONLY_IP
      - HETZNER_TOKEN=$HETZNER_TOKEN
#      - MEDIA_USERNAME=$MEDIA_USERNAME_FOR_WORKERS
#      - MEDIA_PASSWORD=$MEDIA_PASSWORD_FOR_WORKERS
    volumes:
      - jellyfin-conf:/config:z
    restart: always
volumes:
  jellyfin-conf: